version: '3.7'

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_USER: test
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build:
      context: ./api
      dockerfile: dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
    container_name: font
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - api
