version: '3.7'

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_USER: test
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    # No need to expose Nuxt.js port since Nginx will handle the traffic
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Expose HTTP
    volumes:
      - ./front/nginx/default.conf:/etc/nginx/conf.d/default.conf # Nginx configuration file
    depends_on:
      - frontend
