FROM --platform=linux/amd64 gradle:8.3.0-jdk17-alpine as build-image

ENV APP_HOME=/task
WORKDIR $APP_HOME

COPY --chown=gradle:gradle build.gradle settings.gradle $APP_HOME/
COPY --chown=gradle:gradle src $APP_HOME/src


RUN gradle --no-daemon build -x test

RUN ls -1 $APP_HOME/build/libs
########
FROM --platform=linux/amd64 openjdk:17-alpine as runner

ENV APP_HOME=/task

COPY --from=build-image $APP_HOME/build/libs/*.jar app.jar

ENTRYPOINT java -jar app.jar
