version: '3.7'

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_USER: test
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

